spring.application.name=proyecto_final

#Data Base
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect

#hibernate
spring.jpa.hibernate.ddl-auto=validate

#configuracion thymeleaf
spring.thymeleaf.prefix=classpath:/paginas/
spring.thymeleaf.suffix=.html

#Tiempo de la session
server.servlet.session.timeout=30m

#pdf
spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.media-types.pdf=application/pdf

#Configs
server.port=${PORT:8080}